export const LIKE_TRACK = 'LIKE_TRACK';


// PLAYER
export const LIKE_CURR_TRACK = 'PLAYER/LIKE_CURR_TRACK';
export const PICK_PLAYLIST = 'PLAYER/PICK_PLAYLIST';
export const SKIP_TRACK = 'PLAYER/SKIP_TRACK';
export const PLAY_PAUSE_TRACK = 'PLAYER/PLAY_PAUSE_TRACK';
export const MUTED_TRACK = 'PLAYER/MUTED_TRACK';
export const LOOP_TRACK = 'PLAYER/LOOP_TRACK';
export const VOLUME_CHANGE_TRACK = 'PLAYER/VOLUME_CHANGE_TRACK';
export const SEEK_CHANGE_TRACK = 'PLAYER/SEEK_CHANGE_TRACK';
export const SEEK_MOUSE_DOWN_TRACK = 'PLAYER/SEEK_MOUSE_DOWN_TRACK';
export const PROGRESS_TRACK = 'PLAYER/PROGRESS_TRACK';
export const SEEK_MOUSE_UP_TRACK = 'PLAYER/SEEK_MOUSE_UP_TRACK';