const allSongs = [
    {
        id: 1,
        title: "VO52-V1M",
        artist: "20syl",
        img_src: "./images/20syl.jpg",
        src: "./music/20syl - VO52-V1M.mp3",
        favorite: false,
    },
    {
        id: 2,
        title: "A New Error",
        artist: "Moderat",
        img_src: "./images/moderat.jpg",
        src: "./music/Moderat - A New Error.mp3",
        favorite: false,
    },
    {
        id: 3,
        title: "Энтропия",
        artist: "Mujuice",
        img_src: "./images/mujuice.jpg",
        src: "./music/Mujuice - Энтропия.mp3",
        favorite: false,
    },
    {
        id: 4,
        title: "Faint",
        artist: "Quok",
        img_src: "./images/quok.jpg",
        src: "./music/Quok - Faint.mp3",
        favorite: false,
    },
    {
        id: 5,
        title: "Stressed Out",
        artist: "Twenty One Pilots",
        img_src: "./images/tw.gif",
        src: "./music/Twenty One Pilots - Stressed Out.mp3",
        favorite: false,
    },
    {
        id: 6,
        title: "Comptine D'un Autre Été, L'après-Midi",
        artist: "Yann Tiersen",
        img_src: "./images/ameli.jpg",
        src: "./music/Yann_Tiersen_-_Comptine_Dun_Autre_t_Laprs-Midi_48096940.mp3",
        favorite: false,
    },
    {
        id: 7,
        title: "Komorebi",
        artist: "DROELOE",
        img_src: "./images/DROELOE - Komorebi.png",
        src: "./music/DROELOE_-_Komorebi.mp3",
        favorite: false,
    },
    {
        id: 8,
        title: "People",
        artist: "Whitey",
        img_src: "./images/Whitey - People.jpg",
        src: "./music/Whitey - People.mp3",
        favorite: false,
    },
    {
        id: 9,
        title: "Walking All Day",
        artist: "Graham Coxon",
        img_src: "./images/Graham Coxon - Walking All Day.jpg",
        src: "./music/Graham Coxon - Walking All Day.mp3",
        favorite: false,
    },
    {
        id: 10,
        title: "adhd",
        artist: "slowthai",
        img_src: "./images/slowthai - adhd.jpg",
        src: "./music/slowthai - adhd.mp3",
        favorite: false,
    } 
]

export default allSongs